inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lab_inventory.urls')),
    path('users/', include('users.urls')),
]

lab_inventory/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 24 11:31:12 2021

@author: alina

Defines URL patterns for lab_inventory.
"""

from django.urls import path
from . import views

# from django.conf import settings
# from django.conf.urls.static import static

app_name = "lab_inventory"

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # About page
    path('about/', views.about, name='about'),
    # Show all tissues
    path('tissues/', views.tissues, name='tissues'),
    # Show all DNA samples
    path('dna/', views.dna, name='dna'),
    # Show lab supplies
    path('supplies/', views.supplies, name='supplies'),
    # Show PCR primers
    path('primers/', views.primers, name='primers'),
    # Page for adding a new tissue sample
    path('new_tissue/', views.new_tissue, name='new_tissue'),
    # Page for adding a new DNA sample
    path('new_dna/', views.new_dna, name='new_dna'),
    # Page for adding new lab supplies
    path('new_supplies/', views.new_supplies, name='new_supplies'), 
    # Page for adding a new PCR primer
    path('new_primer/', views.new_primer, name='new_primer'),
    # Page for editing a tissue entry
    path('edit_tissue/<int:entry_id>', views.edit_tissue, name='edit_tissue'),
    # Page for editing a DNA entry
    path('edit_dna/<int:entry_id>', views.edit_dna, name='edit_dna'),
    # Page for editing a lab supply entry
    path('edit_supplies/<int:entry_id>', views.edit_supplies, name='edit_supplies'),
    # Page for editing a PCR primer entry
    path('edit_primer/<int:entry_id>', views.edit_primer, name='edit_primer'),
    # Page for choosing filter criteria for the Primer table
    path('choose_filter_primers/', views.choose_filter_primers, name='choose_filter_primers'),
    # Page for querying the Primer table
    path('filter_primers/', views.filter_primers, name='filter_primers'), 
    # Page for displaying primers' search results
    path('search_results_primers/', views.search_results_primers, name='search_results_primers'),
    ]

users/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  7 14:38:03 2021

@author: alina
"""

from django.urls import path
from django.contrib.auth.views import LoginView

# from . import views

app_name = "users"

urlpatterns = [
    # Login page   login is a built-in view, and the dict passes the template to it
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    # Logout page
    # path('logout/', views.logout_view, name='logout'),
    # Registration page
    # path('register/', views.register, name='register'),  # Remove or Use this line?
    ]

lab_inventory/models.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 23 10:00:26 2021

@author: alina
"""

from django.db import models
from django.core.validators import MinValueValidator

class Tissue(models.Model):
    """Information about tissue samples (tissue type and organism)."""
    
    storage_choices = [
    ('Freezer -20', (
        ('-20/1', "Shelf 1"),
        ('-20/2', "Shelf 2"),
        ('-20/3', "Shelf 3"),
        ('-20/4', "Shelf 4"),
        )),
    ('Freezer -80', (
        ('-80/1', "Shelf 1"),
        ('-80/2', "Shelf 2"),
        ('-80/3', "Shelf 3"),
        ('-80/4', "Shelf 4"),
        )),
    ]    
    tissue_info = models.CharField(max_length=200)
    date_received = models.DateField(auto_now=False)
    date_discarded = models.DateField(auto_now=False, null=True, blank=True)
    stored_freezer = models.CharField(max_length=21, choices=storage_choices)
    stored_box = models.CharField(max_length=9)
    
    def __str__(self):
        """Return a string representation of the model."""
        if len(self.tissue_info) > 50:
            return self.tissue_info[:50] + "..."
        else:
            return self.tissue_info


class DNA(models.Model):
    """Information about DNA extracted from tissue samples (tissue type and organism)."""
    
    storage_choices = [
    ('Freezer -20', (
        ('-20/1', "Shelf 1"),
        ('-20/2', "Shelf 2"),
        ('-20/3', "Shelf 3"),
        ('-20/4', "Shelf 4"),
        )),
    ('Freezer -80', (
        ('-80/1', "Shelf 1"),
        ('-80/2', "Shelf 2"),
        ('-80/3', "Shelf 3"),
        ('-80/4', "Shelf 4"),
        )),
    ]
    tissue_choices = [
        ('Solanum lycopersicum', (
            ('Sl - fruit', 'Solanum lycopersicum / fruit'),
            ('Sl - leaf', 'Solanum lycopersicum / leaf'),
            )),
        ('Helianthus annuus', (
            ('Ha - seed', 'Helianthus annuus / seed'),
            ('Ha - leaf', 'Helianthus annuus / leaf'),
            )),
        ('Zea mays', (
            ('Zm - seed', 'Zea mays / seed'),
            ('Zm - leaf', 'Zea mays / leaf'),
            )),
        ('Solanum tuberosum / tuber', (
            ('St - tuber', 'Solanum tuberosum / tuber'),
            ('St - leaf', 'Solanum tuberosum / leaf'),
            )),
        ('Oryza sativa', (
            ('Os - seed', 'Oryza sativa / seed'),
            ('Os - leaf', 'Oryza sativa / leaf'),
            )),
        ('Triticum aestivum', (
            ('Ta - seed', 'Triticum aestivum / seed'),
            ('Ta - leaf', 'Triticum aestivum / leaf'),
            )),
        ]
    
    tissue_info = models.CharField(max_length=100, choices=tissue_choices) # this could also be a ForeignKey instead of CharField
    extraction_date = models.DateField(auto_now=False)
    date_discarded = models.DateField(auto_now=False, null=True, blank=True)
    stored_freezer = models.CharField(max_length=21, choices=storage_choices)
    stored_box = models.CharField(max_length=9)
    
    class Meta:
        verbose_name_plural = 'DNA'

    def __str__(self):
        """Return a string representation of the model."""
        return str(self.tissue_info)


class Supply(models.Model):
    """Information about lab supplies
    (DNA extraction/purification kits, PCR enzymes & reagents).
    """
    
    storage_choices = [
    ('Freezer -20', (
        ('-20/1', "Shelf 1"),
        ('-20/2', "Shelf 2"),
        ('-20/3', "Shelf 3"),
        ('-20/4', "Shelf 4"),
        )),
    ('Freezer -80', (
        ('-80/1', "Shelf 1"),
        ('-80/2', "Shelf 2"),
        ('-80/3', "Shelf 3"),
        ('-80/4', "Shelf 4"),
        )),
    ]
    product_name = models.CharField(max_length=100)
    purchase_order = models.IntegerField(validators=[MinValueValidator(limit_value=0),])
    date_received = models.DateField(auto_now=False)
    date_opened = models.DateField(auto_now=False, null=True, blank=True)
    date_discarded = models.DateField(auto_now=False, null=True, blank=True)
    stored_freezer = models.CharField(max_length=21, choices=storage_choices)
    
    class Meta:
        verbose_name_plural = 'supplies'
    
    def __str__(self):
        """Return a string representation of the model."""
        if len(self.product_name) > 50:
            return self.product_name[:50] + "..."
        else:
            return self.product_name


class Primer(models.Model):
    """Information about PCR primers."""
    
    storage_choices = [
    ('Freezer -20', (
        ('-20/1', "Shelf 1"),
        ('-20/2', "Shelf 2"),
        ('-20/3', "Shelf 3"),
        ('-20/4', "Shelf 4"),
        )),
    ('Freezer -80', (
        ('-80/1', "Shelf 1"),
        ('-80/2', "Shelf 2"),
        ('-80/3', "Shelf 3"),
        ('-80/4', "Shelf 4"),
        )),
    ]
    primer_name = models.CharField(max_length=30)
    primer_seq = models.CharField(max_length=30)
    purchase_order = models.IntegerField(validators=[MinValueValidator(limit_value=0),])
    date_received = models.DateField(auto_now=False)
    date_opened = models.DateField(auto_now=False, null=True, blank=True)
    date_discarded = models.DateField(auto_now=False, null=True, blank=True)
    stored_freezer = models.CharField(max_length=21, choices=storage_choices)
    stored_box = models.CharField(max_length=9)
    
    def __str__(self):
        """Return a string representation of the model."""
        return self.primer_name

lab_inventory/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 27 13:38:24 2021

@author: alina

https://stackoverflow.com/questions/57422465/how-to-get-radio-button-value-from-form-in-view-py-file
"""

from django import forms

from .models import DNA, Primer, Supply, Tissue


### ### ### add new / edit forms ### ### ###

class TissueForm(forms.ModelForm):
    class Meta:
        model = Tissue
        fields = ['tissue_info',
                  'date_received',
                  'date_discarded',
                  'stored_freezer',
                  'stored_box',
                  ]
        labels = {'Organism / Tissue': '',
                  'Date Received': '',
                  'Date Discarded': '',
                  'Freezer / Shelf': '',
                  'Box / Position': '',
                  }


class DNAForm(forms.ModelForm):
    class Meta:
        model = DNA
        fields = ['tissue_info',
                  'extraction_date',
                  'date_discarded',
                  'stored_freezer',
                  'stored_box',
                  ]
        labels = {'Organism / Tissue': '',
                  'Extraction Date': '',
                  'Date Discarded': '',
                  'Freezer / Shelf': '',
                  'Box / Position': '',
                  }


class SupplyForm(forms.ModelForm):
    class Meta:
        model = Supply
        fields = ['product_name',
                  'purchase_order',
                  'date_received',
                  'date_opened',
                  'date_discarded',
                  'stored_freezer',
                  ]
        labels = {'Product Name': '',
                  'Purchase Order': '',
                  'Date Received': '',
                  'Date Opened': '',
                  'Date Discarded': '',
                  'Freezer / Shelf': '',
                  }


class PrimerForm(forms.ModelForm):
    class Meta:
        model = Primer
        fields = ['primer_name',
                  'primer_seq',
                  'purchase_order',
                  'date_received',
                  'date_opened',
                  'date_discarded',
                  'stored_freezer',
                  'stored_box',
                  ]
        labels = {'Primer Name': '',
                  'Primer Sequence': '',
                  'Purchase Order': '',
                  'Date Received': '',
                  'Date Opened': '',
                  'Date Discarded': '',
                  'Freezer / Shelf': '',
                  'Box / Position': '',
                  }

### ### ### filter queryset forms ### ### ###

# Tissues and DNA
CHOOSE_FIELD = [
    ('tissue_info', 'Organism / Tissue'),
    ('date_received', 'Date Received'),
    ('date_opened', 'Date Opened'),
    ('date_discarded', 'Date Discarded'),
    ]

class Tissue_DNA_Radiobtn(forms.Form):
    CHOOSE_FIELD = forms.CharField(widget=forms.RadioSelect(choices=CHOOSE_FIELD,
                                                            attrs={'onchange': 'submit()'}))


# Lab Supplies
CHOOSE_FIELD = [
    ('product_name', 'Product Name'),
    ('purchase_order', 'Purchase Order'),
    ('date_received', 'Date Received'),
    ('date_opened', 'Date Opened'),
    ('date_discarded', 'Date Discarded'),
    ]

class SupplyRadiobtn(forms.Form):
    CHOOSE_FIELD = forms.CharField(widget=forms.RadioSelect(choices=CHOOSE_FIELD,
                                                            attrs={'onchange': 'submit()'}))


# Primers
CHOOSE_FIELD = [
    ('primer_name', 'Primer Name'),
    ('purchase_order', 'Purchase Order'),
    ('date_received', 'Date Received'),
    ('date_opened', 'Date Opened'),
    ('date_discarded', 'Date Discarded'),
    ]

class PrimerRadiobtn(forms.Form):
    CHOOSE_FIELD = forms.CharField(widget=forms.RadioSelect(choices=CHOOSE_FIELD,
                                                            attrs={'onchange': 'submit()'}))


class FilterForm(forms.Form):
    contains = forms.CharField(max_length=100, required=False, initial='')
    exact_match = forms.CharField(max_length=100, required=False, initial='')
    date = forms.DateField(widget=forms.DateInput, required=False, initial='')

    

lab_inventory/templates/lab_inventory/base.html
<!DOCTYPE html>
<html lang="eng-us">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    {% if title %}
        <title>Lab Inventory - {{ title }}</title>
    {% else %}
        <title>Lab Inventory</title>
    {% endif %}
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet"> 
    
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'lab_inventory/base-styles.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon/favicon.png' %}"/>
    
</head>
<body>
  <div class="content-wrap">
    <h1 class="headline">Lab Inventory</h1>
    <div class="subheader-links">
      <a href="{% url 'lab_inventory:index' %}">Home</a>
      <a href="{% url 'lab_inventory:tissues' %}">Tissue Samples</a>
      <a href="{% url 'lab_inventory:dna' %}">DNA</a>
      <a href="{% url 'lab_inventory:supplies' %}">Lab Supplies</a>
      <a href="{% url 'lab_inventory:primers' %}">Primers</a>          
      <span class="login">
      {% if user.is_authenticated %}
        <p>Hello, {{ user.username }}</p>
      {% else %}
        <a href="{% url 'users:login' %}">Log in</a>
      {% endif %}
      </span>
    </div>
    
  {% block content %}{% endblock content %}
  
    <div class="push"></div>
  </div>

  <footer class="footer">
    <span class="github-mark"><a href="https://github.com/alinasansevich/lab-inventory">
      {% load static %}
      <img src="{% static 'lab_inventory/GitHub-Mark-Light-32px.png' %}" alt="GitHub Mark Light"></a>
    </span>
    <span class="author">2021 | Alina Sansevich</span>
    <span class="about">
      <a href="{% url 'lab_inventory:about' %}">About this app</a></span>
  </footer>
</body>
</html> 

lab_inventory/templates/lab_inventory/choose_filter_primers.html
{% extends "lab_inventory/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'lab_inventory/forms-styles.css' %}">

  <div class="container"> 
    <h2>Select filter criteria:</h2>
    <fieldset>
      <legend>Filter by:</legend>
      <form id="radiobtn" action="{% url 'lab_inventory:filter_primers' %}" method="GET">
        {% csrf_token %}
        {{ radiobtn_form.CHOOSE_FIELD }}
      </form>
    </fieldset>
  </div>
        
{% endblock content %}

lab_inventory/templates/lab_inventory/edit_dna.html
{% extends "lab_inventory/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'lab_inventory/forms-styles.css' %}">

  <div class="container">

    <h2>Edit DNA entry:</h3>
      <fieldset>
        <p>Add a new DNA sample below. Enter data in the following format:<br>
         "Organism / Tissue"   |   "2021-01-01"
        </p>
        <form action="{% url 'lab_inventory:edit_dna' entry.id %}" method="post">
          {% csrf_token %}
          <div class="form-wrapper">
            {{ form.non_field_errors }}
            <div class="fieldWrapper">
                {{ form.tissue_info.errors }}
                <label for="id_tissue_info">Organism / Tissue:</label>
                {{ form.tissue_info }}
            </div>
            <div class="fieldWrapper">
                {{ form.extraction_date.errors }}
                <label for="id_extraction_date">Extraction Date:</label>
                {{ form.extraction_date }}
            </div>
            <div class="fieldWrapper">
                {{ form.date_discarded.errors }}
                <label for="id_date_discarded">Date Discarded:</label>
                {{ form.date_discarded }}
            </div>
            <div class="fieldWrapper">
                {{ form.stored_freezer.errors }}
                <label for="id_stored_freezer">Freezer / Shelf:</label>
                {{ form.stored_freezer }}
            </div>
            <div class="fieldWrapper">
                {{ form.stored_box.errors }}
                <label for="id_stored_box">Box / Position:</label>
                {{ form.stored_box }}
            </div>  
          </div>
          <div class="save-goback-btns">
            <button name="submit">Save Changes</button>
            <a class="btns" href="{% url 'lab_inventory:dna' %}">Go back</a>          
          </div>
        </form>
      </fieldset>
  </div>
        
{% endblock content %}

lab_inventory/templates/lab_inventory/edit_primer.html
{% extends "lab_inventory/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'lab_inventory/forms-styles.css' %}">

  <div class="container"> 
    <h2>Edit PCR primer entry:</h2>
      <fieldset>
      <p>Enter dates in the following format: "2021-01-01"</p>
        <form action="{% url 'lab_inventory:edit_primer' entry.id %}" method="post">
          {% csrf_token %}
          <div class="form-wrapper">
            {{ form.non_field_errors }}
            <div class="fieldWrapper">
                {{ form.primer_name.errors }}
                <label for="id_primer_name">Primer Name:</label>
                {{ form.primer_name }}
            </div>
            <div class="fieldWrapper">
                {{ form.primer_seq.errors }}
                <label for="id_primer_seq">Primer Sequence:</label>
                {{ form.primer_seq }}
            </div>
            <div class="fieldWrapper">
                {{ form.purchase_order.errors }}
                <label for="id_purchase_order">Purchase Order:</label>
                {{ form.purchase_order }}
            </div>
            <div class="fieldWrapper">
                {{ form.date_received.errors }}
                <label for="id_date_received">Date Received:</label>
                {{ form.date_received }}
            </div>
            <div class="fieldWrapper">
                {{ form.date_opened.errors }}
                <label for="id_date_opened">Date Opened:</label>
                {{ form.date_opened }}
            </div>
            <div class="fieldWrapper">
                {{ form.date_discarded.errors }}
                <label for="id_date_discarded">Date Discarded:</label>
                {{ form.date_discarded }}
            </div>
            <div class="fieldWrapper">
                {{ form.stored_freezer.errors }}
                <label for="id_stored_freezer">Freezer / Shelf:</label>
                {{ form.stored_freezer }}
            </div>
            <div class="fieldWrapper">
                {{ form.stored_box.errors }}
                <label for="id_stored_box">Box / Position:</label>
                {{ form.stored_box }}
            </div>
          </div>
          <div class="save-goback-btns">
            <button name="submit">Save Changes</button>
            <a class="btns" href="{% url 'lab_inventory:primers' %}">Go back</a>          
          </div>
        </form>
      </fieldset>
  </div>
        
{% endblock content %}

lab_inventory/templates/lab_inventory/edit_supplies.html
{% extends "lab_inventory/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'lab_inventory/forms-styles.css' %}">

  <div class="container"> 
    <h2>Edit supplies entry:</h2>
      <fieldset>
        <p>Enter dates in the following format: "2021-01-01"</p>
        <form action="{% url 'lab_inventory:edit_supplies' entry.id %}" method="post">
          {% csrf_token %}
          <div class="form-wrapper">
            {{ form.non_field_errors }}
            <div class="fieldWrapper">
                {{ form.product_name.errors }}
                <label for="id_product_name">Product Name:</label>
                {{ form.product_name }}
            </div>
            <div class="fieldWrapper">
                {{ form.purchase_order.errors }}
                <label for="id_purchase_order">Purchase Order:</label>
                {{ form.purchase_order }}
            </div>
            <div class="fieldWrapper">
                {{ form.date_received.errors }}
                <label for="id_date_received">Date Received:</label>
                {{ form.date_received }}
            </div>
            <div class="fieldWrapper">
                {{ form.date_opened.errors }}
                <label for="id_date_opened">Date Opened:</label>
                {{ form.date_opened }}
            </div>
            <div class="fieldWrapper">
                {{ form.date_discarded.errors }}
                <label for="id_date_discarded">Date Discarded:</label>
                {{ form.date_discarded }}
            </div> 
            <div class="fieldWrapper">
                {{ form.stored_freezer.errors }}
                <label for="id_stored_freezer">Freezer / Shelf:</label>
                {{ form.stored_freezer }}
            </div>
          </div>
          <div class="save-goback-btns">
            <button name="submit">Save Changes</button>
            <a class="btns" href="{% url 'lab_inventory:supplies' %}">Go back</a>          
          </div>
        </form>
      </fieldset>
  </div>
        
{% endblock content %}

lab_inventory/templates/lab_inventory/edit_tissue.html
{% extends "lab_inventory/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'lab_inventory/forms-styles.css' %}">

  <div class="container"> 
    <h2>Edit tissue entry:</h2>
      <fieldset>
        <p>Add a new tissue sample below. Enter data in the following format:<br>
         "Organism / Tissue"   |   "2021-01-01"
        </p>
        <form action="{% url 'lab_inventory:edit_tissue' entry.id %}" method="post">
          {% csrf_token %}
          <div class="form-wrapper">
            {{ form.non_field_errors }}
            <div class="fieldWrapper">
                {{ form.tissue_info.errors }}
                <label for="id_tissue_info">Organism / Tissue:</label>
                {{ form.tissue_info }}
            </div>
            <div class="fieldWrapper">
                {{ form.date_received.errors }}
                <label for="id_date_received">Date Received:</label>
                {{ form.date_received }}
            </div>
            <div class="fieldWrapper">
                {{ form.date_discarded.errors }}
                <label for="id_date_discarded">Date Discarded:</label>
                {{ form.date_discarded }}
            </div>
            <div class="fieldWrapper">
                {{ form.stored_freezer.errors }}
                <label for="id_stored_freezer">Freezer / Shelf:</label>
                {{ form.stored_freezer }}
            </div>
            <div class="fieldWrapper">
                {{ form.stored_box.errors }}
                <label for="id_stored_box">Box:</label>
                {{ form.stored_box }}
            </div>  
          </div>
          <div class="save-goback-btns">
            <button name="submit">Save Changes</button>
            <a class="btns" href="{% url 'lab_inventory:tissues' %}">Go back</a>          
          </div>
        </form>
      </fieldset>
  </div>
        
{% endblock content %}

lab_inventory/templates/lab_inventory/filter_primers.html
{% extends "lab_inventory/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'lab_inventory/forms-styles.css' %}">

  <div class="container"> 
    <h2>Search by: '{{ filter_by }}'</h2>

    <fieldset>
      <h4>Notes:</h4>
      <ul>
        <li>Enter dates in the following format: "2021-01-01"</li>
        <li>The "Contains..." search field is case insensitive.</li>
      </ul>
    </fieldset>
    <fieldset>
      <legend>Enter search term (use only one at a time):</legend>
      <form action="{% url 'lab_inventory:search_results_primers' %}" method="GET"> <!-- Create e new html for search results??? -->
        {% csrf_token %}
        <div class="form-wrapper">
          {{ form.non_field_errors }}
          <div class="fieldWrapper">
              {{ form.contains.errors }}
              <label for="id_contains">Contains...:</label>
              {{ form.contains }}
              <button class="save-goback-btns" name="submit">Search</button>
          </div>
          <div class="fieldWrapper">
              {{ form.exact_match.errors }}
              <label for="id_exact_match">Exact match:</label>
              {{ form.exact_match }}
              <button class="save-goback-btns" name="submit">Search</button>
          </div>
          <div class="fieldWrapper">
              {{ form.date.errors }}
              <label for="id_date_received">Date:</label>
              {{ form.date }}
              <button class="save-goback-btns" name="submit">Search</button>
          </div>

          </div>
        </div>
      </form>
    </fieldset>
  </div>
        
{% endblock content %}

lab_inventory/templates/lab_inventory/index.html
{% extends "lab_inventory/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'lab_inventory/index-styles.css' %}">
  
  <p id="index-text">Click below to find data about...</p>
  
  <div class="container">  
    
    <a href="{% url 'lab_inventory:tissues' %}">Stored tissues</a>
    <a href="{% url 'lab_inventory:dna' %}">DNA samples</a>
    <a href="{% url 'lab_inventory:supplies' %}">Lab supplies</a>
    <a href="{% url 'lab_inventory:primers' %}">PCR primers</a>
    
  </div>
  
{% endblock content %}

lab_inventory/templates/lab_inventory/new_primer.html
{% extends "lab_inventory/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'lab_inventory/forms-styles.css' %}">

  <div class="container"> 

    <h2>Add a new PCR primer:</h2>
    <fieldset>
      <p>Add a new PCR primer below. Enter dates in the following format: "2021-01-01"</p>
        <form action="{% url 'lab_inventory:new_primer' %}" method="post">
          {% csrf_token %}
          <div class="form-wrapper">
            {{ form.non_field_errors }}
            <div class="fieldWrapper">
                {{ form.primer_name.errors }}
                <label for="id_primer_name">Primer Name:</label>
                {{ form.primer_name }}
            </div>
            <div class="fieldWrapper">
                {{ form.primer_seq.errors }}
                <label for="id_primer_seq">Primer Sequence:</label>
                {{ form.primer_seq }}
            </div>
            <div class="fieldWrapper">
                {{ form.purchase_order.errors }}
                <label for="id_purchase_order">Purchase Order:</label>
                {{ form.purchase_order }}
            </div>
            <div class="fieldWrapper">
                {{ form.date_received.errors }}
                <label for="id_date_received">Date Received:</label>
                {{ form.date_received }}
            </div>
            <div class="fieldWrapper">
                {{ form.date_opened.errors }}
                <label for="id_date_opened">Date Opened:</label>
                {{ form.date_opened }}
            </div>
            <div class="fieldWrapper">
                {{ form.date_discarded.errors }}
                <label for="id_date_discarded">Date Discarded:</label>
                {{ form.date_discarded }}
            </div>
            <div class="fieldWrapper">
                {{ form.stored_freezer.errors }}
                <label for="id_stored_freezer">Freezer / Shelf:</label>
                {{ form.stored_freezer }}
            </div>
            <div class="fieldWrapper">
                {{ form.stored_box.errors }}
                <label for="id_stored_box">Box / Position:</label>
                {{ form.stored_box }}
            </div>
          </div>
          <button name="submit">Add New PCR Primer</button>         
        </form>
    </fieldset>
  </div>
        
{% endblock content %}